import { LogService } from "@bitwarden/logging";
import { AutotypeDriver } from "@bitwarden/sdk-internal";

import type { MainDesktopAutotypeService } from "../main/main-desktop-autotype.service";

/**
 * Applies the enabled state the render process asks for over the encrypted IPC channel.
 *
 * The method name is snake_case because this implements the `AutotypeDriver` interface
 * generated by the SDK. The service is imported as a type only, so the driver adds no
 * runtime dependency back onto the service that constructs it.
 */
export class AutotypeSetEnabledDriver implements AutotypeDriver {
  constructor(
    private autotypeService: MainDesktopAutotypeService,
    private logService: LogService,
  ) {}

  async set_autotype_enabled(enabled: boolean): Promise<boolean> {
    this.logService.info(`Received a request to set the Autotype enabled state to: ${enabled}`);
    return this.autotypeService.setAutotypeEnabled(enabled);
  }
}
