/// Rust target triples for the desktop's native binaries, and the required toolchains.
///
/// Maps between Node platform + set of architectures and Cargo's target triples.

import path from "path";
import type { Architecture, Platform, Profile } from "./build-config.mts";
import { DESKTOP_PROJECT_DIR, runCommand } from "./build-support.mts";
import { glob } from "fs/promises";

export const CARGO_WORKSPACE_DIR = path.resolve(DESKTOP_PROJECT_DIR, "desktop_native");

/// Platforms we can build on. Narrower than NodeJS.Platform, which is why callers pass their
/// own `process.platform` through `asHostPlatform`.
export const HOST_PLATFORMS = ["darwin", "win32", "linux"] as const;
export type HostPlatform = (typeof HOST_PLATFORMS)[number];

export type NodeArch = "ia32" | "x64" | "arm64";

export interface RustTargetDefinition {
  readonly platform: Platform;
  readonly architecture: Exclude<Architecture, "universal">;
  /// Node's names for the same thing, which is what the built files are named after.
  readonly nodePlatform: HostPlatform;
  readonly nodeArch: NodeArch;
}

export const RUST_TARGETS = {
  "i686-pc-windows-msvc": {
    platform: "windows",
    architecture: "ia32",
    nodePlatform: "win32",
    nodeArch: "ia32",
  },
  "x86_64-pc-windows-msvc": {
    platform: "windows",
    architecture: "x64",
    nodePlatform: "win32",
    nodeArch: "x64",
  },
  "aarch64-pc-windows-msvc": {
    platform: "windows",
    architecture: "arm64",
    nodePlatform: "win32",
    nodeArch: "arm64",
  },
  "x86_64-apple-darwin": {
    platform: "macos",
    architecture: "x64",
    nodePlatform: "darwin",
    nodeArch: "x64",
  },
  "aarch64-apple-darwin": {
    platform: "macos",
    architecture: "arm64",
    nodePlatform: "darwin",
    nodeArch: "arm64",
  },
  "x86_64-unknown-linux-gnu": {
    platform: "linux",
    architecture: "x64",
    nodePlatform: "linux",
    nodeArch: "x64",
  },
  "aarch64-unknown-linux-gnu": {
    platform: "linux",
    architecture: "arm64",
    nodePlatform: "linux",
    nodeArch: "arm64",
  },
} as const satisfies Record<string, RustTargetDefinition>;

export type RustTarget = keyof typeof RUST_TARGETS;

/// Triples needed to cover `architectures` on `platform`. A universal macOS build is two
/// separate compilations that @electron/universal merges later, so it expands to two triples.
export function rustTargetsFor(platform: Platform, architecture: Architecture): RustTarget[] {
  const wanted = new Set<Exclude<Architecture, "universal">>();
  if (architecture === "universal") {
    wanted.add("x64");
    wanted.add("arm64");
  } else {
    wanted.add(architecture);
  }

  return rustTargetEntries().flatMap(([triple, definition]) =>
    definition.platform === platform && wanted.has(definition.architecture) ? [triple] : [],
  );
}

function rustTargetEntries(): [RustTarget, RustTargetDefinition][] {
  return Object.entries(RUST_TARGETS) as [RustTarget, RustTargetDefinition][];
}

interface CargoBuildResult {
  /** Lines printed to console, using `--message-format=json` */
  output: string[];

  /**
   * Content of the `filenames` key for the requested package, representing
   * the final output files generated by the compiler.
   */
  filenames?: string[];

  /**
   * depfiles generated by the compiler.
   */
  depFiles?: string[];
}
/**
 * Compiles a Rust package with Cargo. Returns the output from the compiler in JSON format.
 * Cf. https://doc.rust-lang.org/cargo/reference/external-tools.html#json-messages. Note that not all lines will be JSON, so you must handle non-JSON lines.
 * @param Path to `cargo` binary from the config file.
 * @param packageName Package to compile.
 * @param features Features to compile the package with.
 * @param target Rust target.
 * @param profile Build profile.
 */
export async function runCargoBuild(
  cargoBin: string,
  packageName: string,
  features: string[],
  target: RustTarget,
  profile: Profile,
): Promise<CargoBuildResult> {
  const results = await runCargoBuildPackages(cargoBin, [packageName], features, target, profile);
  return results.get(packageName)!;
}

/**
 * Compiles several Rust packages in one Cargo invocation, so that Cargo schedules all of their
 * crates together and compiles shared dependencies once. Note that Cargo unifies features across
 * the packages, so a package may be compiled with more features than when built on its own.
 *
 * @returns The result for each of `packageNames`, as {@link runCargoBuild} returns it.
 */
export async function runCargoBuildPackages(
  cargoBin: string,
  packageNames: string[],
  features: string[],
  target: RustTarget,
  profile: Profile,
  env?: Record<string, string>,
): Promise<Map<string, CargoBuildResult>> {
  const output = (
    await runCommand(
      cargoBin,
      [
        "build",
        "--message-format=json",
        ...packageNames.flatMap((packageName) => ["--package", packageName]),
        "--target",
        target,
        ...(features.length > 0 ? ["--features", features.join(",")] : []),
        ...(profile == "release" ? ["--release"] : []),
      ],
      { cwd: CARGO_WORKSPACE_DIR, env, logLevel: "debug" },
    )
  ).split("\n");

  const results = new Map<string, CargoBuildResult>(
    packageNames.map((packageName) => [packageName, { output }]),
  );
  for (let i = output.length - 1; i > 0; i--) {
    const line = output[i];

    let json;
    try {
      json = JSON.parse(line);
    } catch {
      continue;
    }
    const packageName = json.target?.name;
    if (
      json.reason !== "compiler-artifact" ||
      !results.has(packageName) ||
      results.get(packageName)!.filenames
    ) {
      continue;
    }

    const filenames: string[] = json.filenames;
    const outDir = path.dirname(filenames[0]);
    const depFiles: string[] = [];
    for await (const depFile of glob(`${outDir}/*.d`)) {
      depFiles.push(depFile);
    }
    results.set(packageName, { output, filenames, depFiles });
  }
  return results;
}

/// Workspace packages that depend on napi-derive, and so write type definitions when their
/// macros are expanded.
export async function napiDerivePackages(cargoBin: string): Promise<string[]> {
  const metadata = JSON.parse(
    await runCommand(cargoBin, ["metadata", "--no-deps", "--format-version", "1"], {
      cwd: CARGO_WORKSPACE_DIR,
      logLevel: "debug",
    }),
  );
  return metadata.packages
    .filter((p: { dependencies: { name: string }[] }) =>
      p.dependencies.some((d) => d.name === "napi-derive"),
    )
    .map((p: { name: string }) => p.name);
}
