[package]
name = "desktop_napi"
exclude = ["index.node"]
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }
publish = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
default = []
manual_test = []

[dependencies]
base64 = "=0.22.1"
hex = "=0.4.3"
anyhow = { workspace = true }
desktop_core = { path = "../core" }
napi = { version = "=2.16.15", features = ["async"] }
napi-derive = "=2.16.13"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-registry = "=0.4.0"

[build-dependencies]
napi-build = "=2.1.4"
