/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare namespace autofill {
  /** Response for the lock status of the desktop client. */
  export interface LockStatusResponse {
    /** Whether the desktop client is unlocked. */
    isUnlocked: boolean
  }
  /**
   * Store native desktop status information to use for IPC communication
   * between the application and the credential provider.
   */
  export interface NativeStatus {
    key: string
    value: string
  }
  /** Request to assert a credential. */
  export interface PasskeyAssertionRequest {
    /** Relying Party ID for the request. */
    rpId: string
    /** SHA-256 hash of the `clientDataJSON` for the assertion request. */
    clientDataHash: Array<number>
    /** User verification preference. */
    userVerification: UserVerification
    /** Details about the window of the WebAuthn client. */
    clientWindow: WindowDetails
    /** List of allowed credential IDs. */
    allowedCredentials: Array<Array<number>>
    /**
     * Native context required for callbacks to the OS. Format differs on the OS.
     * # Operating System Differences
     *
     * ## macOS
     * A UUID representing the request.
     *
     * ## Windows
     * On Windows, this is a base64-string representing the following data:
     * `request transaction id (GUID, 16 bytes) || SHA-256(pluginOperationRequest)`
     * The hash is required to be passed back to the OS when calling the
     * Windows Hello passkey user verification API.
     */
    context: string
  }
  /** Response for a passkey assertion request. */
  export interface PasskeyAssertionResponse {
    /** Relying Party ID. */
    rpId: string
    /** The user ID for the credential that was previously given to the OS. */
    userHandle: Array<number>
    /** The signature for the WebAuthn attestation response. */
    signature: Array<number>
    /** SHA-256 hash of the `clientDataJSON` used in the assertion. */
    clientDataHash: Array<number>
    /** The WebAuthn authenticator data structure. */
    authenticatorData: Array<number>
    /** The ID for the attested credential. */
    credentialId: Array<number>
  }
  /** Request to assert a credential without user interaction. */
  export interface PasskeyAssertionWithoutUserInterfaceRequest {
    /** Relying Party ID. */
    rpId: string
    /** SHA-256 hash of the `clientDataJSON` for the assertion request. */
    clientDataHash: Array<number>
    /** User verification preference. */
    userVerification: UserVerification
    /** Details about the window of the WebAuthn client. */
    clientWindow: WindowDetails
    /** The allowed credential ID for the request. */
    credentialId: Array<number>
    /** The user name for the credential that was previously given to the OS. */
    userName?: string
    /** The user ID for the credential that was previously given to the OS. */
    userHandle?: Array<number>
    /**
     * The app-specific local identifier for the credential, in our case, the
     * cipher ID.
     */
    recordIdentifier?: string
    /**
     * Native context required for callbacks to the OS. Format differs on the OS.
     * # Operating System Differences
     *
     * ## macOS
     * A UUID representing the request.
     *
     * ## Windows
     * On Windows, this is `request transaction id () || SHA-256(pluginOperationRequest)`.
     * The hash is required to be passed back to the OS when calling the
     * Windows Hello passkey user verification API.
     */
    context: string
  }
  /** Request to create a credential. */
  export interface PasskeyRegistrationRequest {
    /** Relying Party ID for the request. */
    rpId: string
    /** SHA-256 hash of the `clientDataJSON` for the registration request. */
    clientDataHash: Array<number>
    /** User verification preference. */
    userVerification: UserVerification
    /** Details about the window of the WebAuthn client. */
    clientWindow: WindowDetails
    /** The user name for the credential that was previously given to the OS. */
    userName: string
    /** The user ID for the credential that was previously given to the OS. */
    userHandle: Array<number>
    /** Supported key algorithms in COSE format. */
    supportedAlgorithms: Array<number>
    /** List of excluded credential IDs. */
    excludedCredentials: Array<Array<number>>
    /**
     * Native context required for callbacks to the OS. Format differs by OS.
     * # Operating System Differences
     *
     * ## macOS
     * A UUID representing the request.
     *
     * ## Windows
     * On Windows, this is a base64-string representing the following data:
     * `request transaction id (GUID, 16 bytes) || SHA-256(pluginOperationRequest)`
     * The hash is required to be passed back to the OS when calling the
     * Windows Hello passkey user verification API.
     */
    context: string
  }
  /** Response for a passkey registration request. */
  export interface PasskeyRegistrationResponse {
    /** Relying Party ID. */
    rpId: string
    /** SHA-256 hash of the `clientDataJSON` used in the registration. */
    clientDataHash: Array<number>
    /** The ID for the created credential. */
    credentialId: Array<number>
    /** WebAuthn attestation object. */
    attestationObject: Array<number>
  }
  /** Coordinates representing a point on the screen. */
  export interface Position {
    x: number
    y: number
  }
  /** User verification preference for WebAuthn requests. */
  export const enum UserVerification {
    Preferred = 'preferred',
    Required = 'required',
    Discouraged = 'discouraged'
  }
  /** Details about a native window. */
  export interface WindowDetails {
    /**
     * Coordinates of the center of the window, relative to
     * the top-left point on the screen.
     * # Operating System Differences
     *
     * ## macOS
     * Note that macOS APIs gives points relative to the bottom-left point on the
     * screen by default, so the y-coordinate will be flipped.
     *
     * ## Windows
     * On Windows, this must be logical pixels, not physical pixels.
     */
    position: Position
    /**
     * Byte string representing the native OS window handle.
     * # Operating System Differences
     *
     * ## macOS
     * Unused.
     *
     * ## Windows
     * On Windows, this is a HWND.
     */
    handle?: Array<number>
  }
  /** Response to window handle request. */
  export interface WindowHandleQueryResponse {
    /** Whether the desktop client is currently visible. */
    isVisible: boolean
    /** Whether the desktop client is currently focused. */
    isFocused: boolean
    /**
     * Byte string representing the native OS window handle for the desktop client.
     * # Operating System Differences
     *
     * ## macOS
     * Unused.
     *
     * ## Windows
     * On Windows, this is a HWND.
     */
    handle: Array<number>
  }
}
export declare namespace agent_access {
  /** Wrapper for Electron to interface with the Agent Access desktop integration. */
  export class AgentAccessState {
    /**
     * Connects to the relay, optionally starts the local listener, and starts serving
     * credential requests from both.
     *
     * # Arguments
     *
     * * `config` - Relay URL and (optional) local socket/pipe path.
     * * `credential_callback` - Looks the credential up in the unlocked vault and prompts
     *   the user for approval.
     * * `fingerprint_callback` - Prompts the user to verify a rendezvous handshake
     *   fingerprint. Always invoked for rendezvous pairings — never auto-approved.
     * * `storage_get_callback` / `storage_set_callback` - Back identity/connection/PSK
     *   persistence (e.g. the OS keychain).
     * * `event_callback` - Receives a best-effort activity-log event stream (connections,
     *   credential requests, relay reconnects, ...) for the desktop's activity log.
     *   Fire-and-forget: invoked under a short timeout, and any failure/timeout is
     *   discarded — it can never affect protocol behavior.
     */
    static serve(config: AgentAccessConfig, credentialCallback: ((err: Error | null, arg: CredentialRequestData) => Promise<CredentialResponseData>), fingerprintCallback: ((err: Error | null, arg: FingerprintVerificationData) => Promise<FingerprintVerificationResponse>), storageGetCallback: ((err: Error | null, arg: string) => Promise<string | undefined | null>), storageSetCallback: ((err: Error | null, arg: StorageEntry) => Promise<undefined>), eventCallback: ((err: Error | null, arg: AgentAccessEvent) => Promise<undefined>)): Promise<AgentAccessState>
    stop(): void
    /**
     * Starts (path) or stops (null/undefined) the OpenShell listener. Idempotent.
     *
     * The path is computed by the main process, never taken from the renderer (§M8.8).
     */
    setOpenShellListener(socketPath?: string | undefined | null): Promise<void>
    isRunning(): boolean
    getFingerprint(): Promise<string>
    generatePskToken(name: string | undefined | null, reusable: boolean): Promise<string>
    generateRendezvousCode(name?: string | undefined | null): Promise<string>
    listConnections(): Promise<Array<ConnectionInfoData>>
    removeConnection(fingerprint: string): Promise<void>
  }
  /** Configuration for [`AgentAccessState::serve`]. */
  export interface AgentAccessConfig {
    /** WebSocket URL of the Agent Access relay. */
    relayUrl: string
    /**
     * Path to the local Unix socket / Windows named pipe to listen on for the `aac` CLI.
     * Main-process-owned: computed by `MainAgentAccessService`, never sourced from the
     * renderer's `INIT` payload. `undefined`/`null` skips the local listener entirely.
     */
    socketPath?: string
  }
  /**
   * A single agent-access activity event for the desktop's live activity log.
   *
   * SECURITY: never carries credential values, PSKs, tokens, or key material — see
   * `agent_access_core::AgentAccessEvent`'s docs, which this mirrors field-for-field.
   */
  export interface AgentAccessEvent {
    kind: string
    /** Unix epoch milliseconds, stringified to avoid JS numeric-precision surprises. */
    timestampMs: string
    peerFingerprint?: string
    peerName?: string
    detail?: string
    /**
     * Comma-joined field names released by a `credentialApproved` event (e.g.
     * `"username,password,totp"`).
     */
    fieldsShared?: string
  }
  /**
   * One entry of an approved `operation: "list"` response (M6, `projectList`) — project
   * metadata only, no secret material. `organization` is the org's display name, resolved
   * renderer-side.
   */
  export interface AgentAccessProjectEntry {
    id: string
    name: string
    write: boolean
    organization?: string
  }
  /**
   * One entry of an approved `operation: "bulkRequest"` response (M7,
   * `projectSecretsRequest`). Unlike [`AgentAccessProjectEntry`] this carries a live secret
   * value — no `#[derive(Debug)]`: the manual impl below prints presence/count only (`id` is
   * an opaque identifier, printed verbatim; `name`/`value` are redacted, darker than
   * [`AgentAccessProjectEntry`]'s plain derive), and nothing outside the in-flight response
   * path may hold one.
   */
  export interface AgentAccessSecretEntry {
    id: string
    name: string
    value: string
  }
  /** Summary of a cached connection for the `listConnections()` surface. */
  export interface ConnectionInfoData {
    fingerprint: string
    name?: string
    /** Unix timestamp (seconds), stringified to avoid any JS numeric-precision surprises. */
    cachedAt?: string
    /** Unix timestamp (seconds), stringified to avoid any JS numeric-precision surprises. */
    lastConnectedAt?: string
  }
  /** Which field of a [`CredentialRequestData`] the query matches against. */
  export const enum CredentialQueryType {
    Domain = 'domain',
    Id = 'id',
    Search = 'search',
    /**
     * Exact (or unique case-insensitive) Secrets Manager secret key match. Valid only for
     * `resourceType: "secret"` requests.
     */
    Name = 'name'
  }
  /**
   * A credential lookup — or, for `operation: "create"`, a proposed secret creation —
   * requested by a paired remote agent or the local `aac` CLI, sent to Electron for approval.
   *
   * Not `#[derive(Debug)]`: `new_secret_value` carries a plaintext secret across the FFI
   * boundary (Electron needs it to render the masked-with-reveal value field), so it must
   * never end up formatted into a log line — see the manual `Debug` impl below, which mirrors
   * `agent_access_core::CredentialRequestData`'s redaction of the same field.
   */
  export interface CredentialRequestData {
    queryType: CredentialQueryType
    queryValue: string
    /** `None` for `origin: "local"` — local requesters have no cryptographic identity. */
    requesterFingerprint?: string
    requesterName?: string
    origin: CredentialRequestOrigin
    /** `None` on the relay path. */
    localPeer?: LocalPeerInfoData
    /** `None` on the relay path, and for `operation: "create"` requests. */
    deliveryMode?: DeliveryMode
    /**
     * Whether this request is asking for a login credential or a Secrets Manager secret.
     * Always `"credential"` on the relay path.
     */
    resourceType: ResourceType
    /**
     * Whether this is a lookup against existing vault data, or a proposal to create a new
     * Secrets Manager secret. Always `"request"` on the relay path.
     */
    operation: OperationType
    /** Proposed name for a new Secrets Manager secret. Only set for `operation: "create"`. */
    newSecretName?: string
    /**
     * Proposed value for a new Secrets Manager secret. Only set for `operation: "create"`.
     * Held in plaintext here because Electron needs it to render the masked-with-reveal
     * value field in the creation-approval dialog — the same reason `secret_value` on
     * [`CredentialResponseData`] crosses this boundary as a plain `String` rather than
     * staying `Zeroizing`.
     */
    newSecretValue?: string
    /** Proposed note for a new Secrets Manager secret. Only set for `operation: "create"`. */
    newSecretNote?: string
    /**
     * Optional project-name hint for a new Secrets Manager secret — never trusted silently,
     * see `agent_access_core::CredentialRequestData::project_hint`'s docs. Set for
     * `operation: "create"`, and for `operation: "update"` when the agent proposes a
     * project move (M6).
     */
    projectHint?: string
    /**
     * Id of the existing secret or project an `operation: "update"`/`"delete"` request
     * targets (M6), or of the project an `operation: "bulkRequest"` selects by id (M7).
     * An opaque identifier, never a name or value.
     */
    targetId?: string
    /**
     * Project name an `operation: "bulkRequest"` selects by name (M7) — mutually
     * exclusive with `targetId` for that operation (enforced in
     * `local_protocol::validate`). Resolved renderer-side against the user's readable
     * projects; never trusted as an exact identity. Unset for every other operation.
     *
     * Not carried as a distinct field on `agent_access_core::CredentialRequestData` — the
     * core crate reuses `query_value` for the name form (see that field's docs); this
     * field is derived from `operation`/`target_id`/`query_value` in the `From` impl
     * below, purely to give the napi/TS surface an unambiguous, purpose-specific field
     * rather than requiring the renderer to infer "is this a name?" from `query_value`.
     */
    projectName?: string
    /**
     * When true, the desktop generates the secret's value at approval time instead of the
     * agent supplying one (M6): renderer-side generation, org-key encryption, then discard —
     * the value never crosses this boundary in either direction. Mutually exclusive with
     * `newSecretValue` (enforced in `local_protocol::validate`). Valid for
     * `operation: "create"` and `"update"` on `resourceType: "secret"`.
     */
    generateValue?: boolean
    /**
     * Requested generated-value length, already validated to `[12, 128]` by the wire layer.
     * Absent means the desktop default (40). Only set alongside `generateValue: true`.
     */
    generateLength?: number
    /**
     * Whether the generated value includes symbols (default true). Only set alongside
     * `generateValue: true`.
     */
    generateSymbols?: boolean
    /**
     * Requested field roles (`"username"`/`"password"`/`"totp"`) for a
     * `deliveryMode: "fill"` request (M5). `None`/absent means "default: all fields present
     * and safe". Value-free — role names, never a credential value.
     */
    fillFields?: Array<string>
    /**
     * Optional `targetToken` from a prior `describeFillTarget` call (M5), binding this fill
     * to a specific extension-produced field plan. Value-free — an opaque token.
     */
    fillTargetToken?: string
    /**
     * Gateway-reported context for `operation: "providerResolve"` (§M8). Only set for
     * `origin: "openshell"`.
     */
    openshell?: OpenShellContextData
    /**
     * The `bw://` targets of `operation: "providerResolve"`, in wire order. Only set for
     * `origin: "openshell"`.
     */
    providerTargets?: Array<ProviderTargetData>
  }
  /** Which ingress a [`CredentialRequestData`] arrived through. */
  export const enum CredentialRequestOrigin {
    Relay = 'relay',
    Local = 'local',
    /** The toggle-gated OpenShell socket (§M8). Set by the listener kind, never the wire. */
    OpenShell = 'openshell'
  }
  /**
   * Electron's answer to a [`CredentialRequestData`]. Not `Debug`/`Clone` — it may carry a
   * live credential, and nothing here should ever end up formatted into a log line.
   */
  export interface CredentialResponseData {
    approved: boolean
    username?: string
    password?: string
    totp?: string
    uri?: string
    notes?: string
    credentialId?: string
    /**
     * Set when `approved: false` to distinguish "no match" (`"notFound"`) from an explicit
     * user denial (`"denied"`), a locked/unavailable vault (`"locked"`), or a non-user
     * failure (`"error"` — e.g. the feature was disabled, or a lookup failed). Any other
     * value (including `None`) maps to the generic "denied" default on the local
     * protocol's `status` field. `"locked"`/`"error"` exist so those cases are never
     * reported to the requester as "Denied by user" — see
     * `agent_access_core::CredentialDenialReason`'s docs.
     */
    reason?: string
    /**
     * Display name of the matched item, for the local protocol's reference-mode reply.
     * Not yet populated by the renderer — see `MainAgentAccessService`'s report. Also
     * doubles as the Secrets Manager secret's display name (`secret.name`) for
     * `resourceType: "secret"` requests.
     */
    itemName?: string
    /**
     * The Secrets Manager secret's decrypted value, for `resourceType: "secret"` requests.
     * Unset for credential requests.
     */
    secretValue?: string
    /**
     * Secrets Manager secret ID, for `resourceType: "secret"` requests. Unset for
     * credential requests.
     */
    secretId?: string
    /**
     * Secrets Manager project ID, for approved `resourceType: "project"`
     * create/update/delete responses (M6). Unset otherwise.
     */
    projectId?: string
    /**
     * The readable project list released by an approved `operation: "list"` request (M6) —
     * names, ids, and write flags only, no secret material. The names transit main only
     * inside this in-flight response and are never buffered there (ids-only activity
     * invariant). Unset for every other operation.
     */
    projects?: Array<AgentAccessProjectEntry>
    /**
     * The secret set released by an approved `operation: "bulkRequest"` request (M7,
     * `projectSecretsRequest`) — one entry per secret the user saw enumerated in the
     * approval dialog. Carries live secret VALUES: entries transit main only inside this
     * in-flight response and are never buffered there (the activity row keeps ids only,
     * via `secretIds` on the outcome). Unset for every other operation.
     */
    secrets?: Array<AgentAccessSecretEntry>
    /**
     * Value-free JSON pass-through describing a `deliveryMode: "fill"` request's execution
     * outcome (M5's `fill` response object) — the renderer builds this directly (its shape
     * mirrors the wire example in agent-access-architecture.md's "M5" section). Parsed into
     * a `serde_json::Value` by `agent_access_core::local_listener::local_protocol`; never
     * read as a field by this crate. Set for `deliveryMode: "fill"` responses, approved or
     * denied (an `originMismatch`/`noSafeTarget` denial can still carry the
     * extension-reported origin here).
     */
    fillResult?: string
    /**
     * Value-free JSON pass-through describing the active browser tab for a
     * `operation: "describeFillTarget"` request (M5's `fillTarget` response object). Set
     * only for `describeFillTarget` responses.
     */
    fillTarget?: string
    /**
     * Machine-readable, value-free detail for an `"originMismatch"`/`"noSafeTarget"`
     * `reason` (the mismatched origin, or a `looks-like-registration`/`ambiguous-target`/...
     * reason code), or actionable static guidance for an `"error"` reason (e.g. "the
     * browser extension is not connected"). `None` for every other reason, and optional
     * even for these — the wire layer falls back to a generic message when it is absent.
     *
     * NEVER put a vault value here: this string is relayed verbatim to the requesting
     * agent by `local_protocol.rs`'s denial dispatch.
     */
    denialDetail?: string
    /**
     * Field roles (`"username"`/`"password"`/`"totp"`) actually filled by an approved
     * `deliveryMode: "fill"` request, for the activity log's `fieldsShared` (M5). Supplied
     * directly by the renderer rather than derived by parsing `fill_result`.
     */
    fillFieldsShared?: Array<string>
    /**
     * The released values for an approved `operation: "providerResolve"` request (§M8), in
     * target order. The Rust reply builder re-checks the key set before writing anything.
     */
    openshellValues?: Array<ProviderValueData>
    /** The approval lifetime for an approved `operation: "providerResolve"` request (§M8). */
    openshellLifetime?: OpenShellLifetimeData
  }
  /**
   * How the requester wants an approved credential delivered. Only present for
   * `origin: "local"` requests.
   */
  export const enum DeliveryMode {
    Inject = 'inject',
    Reference = 'reference',
    /**
     * M5, "Browser fill delivery" — the credential value never crosses this napi boundary
     * at all for this mode; the renderer resolves it and pushes it directly to the browser
     * extension. Credential resource only.
     */
    Fill = 'fill'
  }
  /** A handshake fingerprint pending user verification (rendezvous pairing only). */
  export interface FingerprintVerificationData {
    fingerprint: string
    identityFingerprint: string
  }
  /** Electron's answer to a [`FingerprintVerificationData`]. */
  export interface FingerprintVerificationResponse {
    approved: boolean
    name?: string
  }
  /**
   * OS-verified identity of the local peer (the `aac` CLI process), captured at accept time
   * from peer credentials — never self-reported. `None` fields mean resolution failed for
   * that piece of metadata, not that the peer is untrusted; see
   * `agent_access_core::LocalPeerInfo`'s docs.
   */
  export interface LocalPeerInfoData {
    pid: number
    processName?: string
    exePath?: string
    parent?: ParentProcessInfoData
    signature?: SignatureInfoData
  }
  /**
   * Gateway-reported context for an `operation: "providerResolve"` request (§M8.7). Every
   * field is reported by the OpenShell gateway, not verified by Bitwarden.
   */
  export interface OpenShellContextData {
    deadlineMs: number
    gatewayName: string
    gatewayEndpoint: string
    providerId: string
    providerName: string
    providerProfile: string
    workspace: string
    sandboxId: string
    sandboxName: string
    sandboxImage?: string
    endpoints: Array<OpenShellEndpointData>
    policyDigest: string
    advisorEnabled?: boolean
  }
  /**
   * One endpoint an OpenShell provider credential can be sent to — reported by the gateway,
   * not verified by Bitwarden.
   */
  export interface OpenShellEndpointData {
    host: string
    port: number
    path?: string
    source: OpenShellEndpointSource
  }
  /** Which source an [`OpenShellEndpointData`] came from (§M8.5). */
  export const enum OpenShellEndpointSource {
    Profile = 'profile',
    PolicyBinding = 'policyBinding'
  }
  /**
   * The approval lifetime the renderer chose. `expiresAtMs` is a stringified u64 (Unix epoch
   * milliseconds), like `timestampMs`: required for `perRequest`/`ttl`, absent for
   * `sandboxLifetime` — enforced again by the Rust reply builder.
   */
  export interface OpenShellLifetimeData {
    mode: OpenShellLifetimeMode
    expiresAtMs?: string
  }
  /** How long one OpenShell approval lasts (§M8.6). */
  export const enum OpenShellLifetimeMode {
    PerRequest = 'perRequest',
    Ttl = 'ttl',
    SandboxLifetime = 'sandboxLifetime'
  }
  /**
   * Whether a [`CredentialRequestData`] is asking to look up existing vault data, to
   * create a new Secrets Manager secret (M4b, `secretCreate`), or to describe the active
   * browser tab's fillable fields (M5, `describeFillTarget`). Always `"request"` on the
   * relay path — creates and describe-target requests are local-transport-only, same
   * restriction as `resourceType: "secret"` (see agent-access-architecture.md, "M4b — secret
   * creation" and "M5 — Browser fill delivery").
   */
  export const enum OperationType {
    Request = 'request',
    Create = 'create',
    /** Update an existing SM secret, or rename a project (M6, `secretUpdate`/`projectUpdate`). */
    Update = 'update',
    /** Delete a single SM secret or project (M6, `secretDelete`/`projectDelete`). */
    Delete = 'delete',
    /** Release the readable SM project list in one approval (M6, `projectList`). */
    List = 'list',
    /**
     * Release ALL secrets of one project for env injection into one command (M7,
     * `projectSecretsRequest`) — the sole bulk read; fully enumerated in the approval
     * dialog, capped at 200, local-transport-only like every non-`request` operation.
     */
    BulkRequest = 'bulkRequest',
    DescribeFillTarget = 'describeFillTarget',
    /**
     * An OpenShell gateway resolving one provider's `bw://` references (§M8,
     * `openshellResolve`). Only ever paired with `origin: "openshell"`.
     */
    ProviderResolve = 'providerResolve'
  }
  /**
   * Best-effort one-level parent-chain walk from the local peer (W2a, `crate::attestation`
   * in `agent_access_core`) — identifies whoever spawned the `aac` CLI (the agent), since the
   * socket peer itself is always `aac`. `None` on `LocalPeerInfoData::parent` means the walk
   * failed or hit `launchd`/`init` — see `agent_access_core::attestation`'s docs — not that
   * the peer is untrusted.
   */
  export interface ParentProcessInfoData {
    pid: number
    processName?: string
    exePath?: string
  }
  /** Which field of an item or secret a [`ProviderTargetData`] names (§M8.3). */
  export const enum ProviderField {
    Username = 'username',
    Password = 'password',
    Value = 'value'
  }
  /**
   * One `bw://` target of a provider resolve: an env-var name plus the item or secret id.
   * Value-free.
   */
  export interface ProviderTargetData {
    credentialKey: string
    resourceType: ResourceType
    id: string
    field: ProviderField
  }
  /** One released provider credential value. Not `Debug`: it carries a live value. */
  export interface ProviderValueData {
    credentialKey: string
    value: string
  }
  /**
   * Which kind of vault data a [`CredentialRequestData`] is asking for. Always `"credential"`
   * on the relay path — Secrets Manager secrets are local-transport-only (see
   * agent-access-architecture.md, "M4", invariant 6).
   */
  export const enum ResourceType {
    Credential = 'credential',
    Secret = 'secret',
    /** Secrets Manager project (M6) — list/create/update/delete operations only. */
    Project = 'project'
  }
  /**
   * Code-signature facts (W2a) about the attested process — the resolved `parent` if
   * present, else the immediate peer. An unsigned or invalid-signature binary still produces
   * a `SignatureInfoData` with `valid: false` and the best available `identity` (falling back
   * to the executable path) — `None` on `LocalPeerInfoData::signature` means verification
   * could not be attempted at all.
   */
  export interface SignatureInfoData {
    kind: SignatureKindData
    identity: string
    valid: boolean
  }
  /**
   * Which platform mechanism produced a [`SignatureInfoData`], and therefore how to read
   * `identity`.
   */
  export const enum SignatureKindData {
    MacosTeamId = 'macosTeamId',
    WindowsPublisher = 'windowsPublisher',
    LinuxPathOnly = 'linuxPathOnly'
  }
  /** One key/value pair for the `storageSetCallback`. `value: None` means "delete this key". */
  export interface StorageEntry {
    key: string
    value?: string
  }
}

export declare namespace autofill {
  export class AutofillIpcServer {
    /**
     * Create and start the IPC server without blocking.
     *
     * @param name The endpoint name to listen on. This name uniquely identifies the IPC
     * connection and must be the same for both the server and client. @param callback
     * The functions that will be called whenever a message of the
     * corresponding type is received from a client.
     */
    static listen(name: string, callbacks: AutofillIpcCallbacks): Promise<AutofillIpcServer>
    /** Return the path to the IPC server. */
    getPaths(): Array<string>
    /** Stop the IPC server. */
    stop(): void
    completeRegistration(clientId: number, sequenceNumber: number, response: PasskeyRegistrationResponse): number
    completeAssertion(clientId: number, sequenceNumber: number, response: PasskeyAssertionResponse): number
    completeLockStatus(clientId: number, sequenceNumber: number, response: LockStatusResponse): number
    completeWindowHandleQuery(clientId: number, sequenceNumber: number, response: WindowHandleQueryResponse): number
    completeError(clientId: number, sequenceNumber: number, error: string): number
  }
  export interface AutofillIpcCallbacks {
    /**
     * Function to execute when a passkey registration request is received.
     *
     * The `context` field should be stored, as the cancel_request_callback
     * will use the same value to identify the request to be cancelled.
     */
  registrationCallback: { (error: null, clientId: number, sequenceNumber: number, message: PasskeyRegistrationRequest): void; (error: Error, clientId: number, sequenceNumber: number, message: null): void; }
  /**
   * Function to execute when a passkey assertion request is received.
   *
   * The `context` field should be stored, as the cancel_request_callback
   * will use the same value to identify the request to be cancelled.
   */
  assertionCallback: { (error: null, clientId: number, sequenceNumber: number, message: PasskeyAssertionRequest): void; (error: Error, clientId: number, sequenceNumber: number, message: null): void; }
  /**
   * Function to execute when a passkey assertion request is received and the UI must not be
   * shown.
   *
   * The `context` field should be stored, as the cancel_request_callback
   * will use the same value to identify the request to be cancelled.
   */
  assertionWithoutUserInterfaceCallback: { (error: null, clientId: number, sequenceNumber: number, message: PasskeyAssertionWithoutUserInterfaceRequest): void; (error: Error, clientId: number, sequenceNumber: number, message: null): void; }
  /** Function to execute when a notification of the autofill provider's status is received. */
  nativeStatusCallback: { (error: null, clientId: number, sequenceNumber: number, message: NativeStatus): void; (error: Error, clientId: number, sequenceNumber: number, message: null): void; }
  /** Function to execute to retrieve the lock status of the vault. */
  lockStatusCallback: { (error: null, clientId: number, sequenceNumber: number): void; (error: Error, clientId: number, sequenceNumber: number, message: null): void; }
  /** Function to execute to retrieve the native OS window handle of the main application. */
  windowHandleQueryCallback: { (error: null, clientId: number, sequenceNumber: number): void; (error: Error, clientId: number, sequenceNumber: number, message: null): void; }
  /**
   * Function to cancel a request. The `message` parameter is the context
   * string that was passed on the initial request.
   */
  cancelRequestCallback: { (error: null, clientId: number, sequenceNumber: number, message: string): void; (error: Error, clientId: number, sequenceNumber: number, message: null): void; }
  }
  export function runCommand(value: string): Promise<string>
}

export declare namespace autostart {
  export interface AutostartConfig {
    execPath: string
    autostartFlag: string
  }
  export function setAutostart(enabled: boolean, config: AutostartConfig): Promise<void>
}

export declare namespace autotype_mvp {
  export function getForegroundWindowTitle(): string
  export function typeInput(input: Array<number>, keyboardShortcut: Array<string>): void
}

export declare namespace biometrics {
  export class BiometricLockSystem {

  }
  export function authenticate(biometricLockSystem: BiometricLockSystem, hwnd: Buffer, message: string): Promise<boolean>
  export function authenticateAvailable(biometricLockSystem: BiometricLockSystem): Promise<boolean>
  export function enrollPersistent(biometricLockSystem: BiometricLockSystem, userId: string, key: Buffer): Promise<void>
  export function hasPersistent(biometricLockSystem: BiometricLockSystem, userId: string): Promise<boolean>
  export function initBiometricSystem(): BiometricLockSystem
  export function provideKey(biometricLockSystem: BiometricLockSystem, userId: string, key: Buffer): Promise<void>
  export function unenroll(biometricLockSystem: BiometricLockSystem, userId: string): Promise<void>
  export function unlock(biometricLockSystem: BiometricLockSystem, userId: string, hwnd: Buffer): Promise<Buffer>
  export function unlockAvailable(biometricLockSystem: BiometricLockSystem, userId: string): Promise<boolean>
}

export declare namespace chromium_importer {
  export function getAvailableProfiles(browser: string, masBuild: boolean): Promise<Array<ProfileInfo>>
  /** Returns OS aware metadata describing supported Chromium based importers as a JSON string. */
  export function getMetadata(masBuild: boolean): Record<string, NativeImporterMetadata>
  export function importLogins(browser: string, profileId: string, masBuild: boolean): Promise<Array<LoginImportResult>>
  export interface Login {
    url: string
    username: string
    password: string
    note: string
  }
  export interface LoginImportFailure {
    url: string
    username: string
    error: string
  }
  export interface LoginImportResult {
    login?: Login
    failure?: LoginImportFailure
  }
  export interface NativeImporterMetadata {
    id: string
    loaders: Array<string>
    instructions: string
  }
  /** Pre-translated picker dialog strings supplied by the renderer. */
  export interface PickerStrings {
    message: string
    expectedLocationLabel: string
    prompt: string
  }
  export interface ProfileInfo {
    id: string
    name: string
  }
  export function requestBrowserAccess(browser: string, pickerStrings: PickerStrings, masBuild: boolean): Promise<void>
}

export declare namespace clipboards {
  export function read(): Promise<string>
  export function write(text: string, password: boolean): Promise<void>
}

export declare namespace ipc {
  export class NativeIpcServer {
    /**
     * Create and start the IPC server without blocking.
     *
     * @param name The endpoint name to listen on. This name uniquely identifies the IPC
     * connection and must be the same for both the server and client. @param callback
     * This function will be called whenever a message is received from a client.
     */
    static listen(name: string, callback: (error: null | Error, message: IpcMessage) => void): Promise<NativeIpcServer>
    /** Return the paths to the IPC server. */
    getPaths(): Array<string>
    /** Stop the IPC server. */
    stop(): void
    /**
     * Send a message over the IPC server to all the connected clients
     *
     * @return The number of clients that the message was sent to. Note that the number of
     * messages actually received may be less, as some clients could disconnect before
     * receiving the message.
     */
    send(message: string): number
    /** Send a message to a specific connected client by ID. */
    sendTo(clientId: number, message: string): void
  }
  export interface IpcMessage {
    clientId: number
    kind: IpcMessageType
    message?: string
  }
  export const enum IpcMessageType {
    Connected = 0,
    Disconnected = 1,
    Message = 2
  }
}

export declare namespace logging {
  export function initNapiLog(jsLogFn: ((err: Error | null, arg0: LogLevel, arg1: string) => any)): void
  export const enum LogLevel {
    Trace = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4
  }
}

export declare namespace passkey_authenticator {
  export function register(): void
}

export declare namespace passwords {
  /**
   * Delete the stored password from the keychain.
   * Throws {@link Error} with message {@link PASSWORD_NOT_FOUND} if the password does not exist.
   */
  export function deletePassword(service: string, account: string): Promise<void>
  /**
   * Fetch the stored password from the keychain.
   * Throws {@link Error} with message {@link PASSWORD_NOT_FOUND} if the password does not exist.
   */
  export function getPassword(service: string, account: string): Promise<string>
  /** Checks if the os secure storage is available */
  export function isAvailable(): Promise<boolean>
  /** The error message returned when a password is not found during retrieval or deletion. */
  export const PASSWORD_NOT_FOUND: string
  /**
   * Save the password to the keychain. Adds an entry if none exists otherwise updates the
   * existing entry.
   */
  export function setPassword(service: string, account: string, password: string): Promise<void>
}

export declare namespace powermonitors {
  export function isLockMonitorAvailable(): Promise<boolean>
  export function onLock(callback: ((err: Error | null, ) => any)): Promise<void>
}

export declare namespace processisolations {
  export function disableCoredumps(): Promise<void>
  export function isCoreDumpingDisabled(): Promise<boolean>
  export function isolateProcess(): Promise<void>
}

export declare namespace sshagent {
  export class SshAgentState {

  }
  export function clearKeys(agentState: SshAgentState): void
  export function isRunning(agentState: SshAgentState): boolean
  export function lock(agentState: SshAgentState): void
  export interface PrivateKey {
    privateKey: string
    name: string
    cipherId: string
  }
  export function serve(callback: ((err: Error | null, arg: SshUiRequest) => Promise<boolean>)): Promise<SshAgentState>
  export function setKeys(agentState: SshAgentState, newKeys: Array<PrivateKey>): void
  export interface SshKey {
    privateKey: string
    publicKey: string
    keyFingerprint: string
  }
  export interface SshUiRequest {
    cipherId?: string
    isList: boolean
    processName: string
    isForwarding: boolean
    namespace?: string
  }
  export function stop(agentState: SshAgentState): void
}

export declare namespace sshagent_v2 {
  /** Wrapper for Electron to be able to interface with the agent directly. */
  export class SshAgentState {
    /**
     * Creates a new [`BitwardenSSHAgent`] and starts the server.
     *
     * # Arguments
     *
     * * `sign_callback` - Allows agent to get approval for sign requests
     * * `list_callback` - Allows agent to get approval for list key requests
     */
    static serve(signCallback: ((err: Error | null, arg: SignRequestData) => Promise<boolean>), listCallback: ((err: Error | null, ) => Promise<boolean>)): Promise<SshAgentState>
    stop(): void
    isRunning(): boolean
    replace(newKeys: Array<SshKeyData>): void
  }
  export type SSHAgentState = SshAgentState
  /** SSH public key data */
  export interface PublicKey {
    alg: string
    blob: Array<number>
  }
  /** A sign request's SIG namespace */
  export const enum SIGNamespace {
    Git = 'git',
    File = 'file',
    Unsupported = 'unsupported'
  }
  /** SSH sign request fields. */
  export interface SignRequest {
    publicKey: PublicKey
    processName?: string
    isForwarding: boolean
    namespace?: SIGNamespace
    hostFingerprint?: string
  }
  /** Data for a sign request, including vault cipher context. */
  export interface SignRequestData {
    signRequest: SignRequest
    cipherId?: string
  }
  /** SSH key data, sent from Electron. */
  export interface SshKeyData {
    privateKey: string
    name: string
    cipherId: string
  }
}

export declare namespace windows_registry {
  export function createKey(key: string, subkey: string, value: string): Promise<void>
  export function deleteKey(key: string, subkey: string): Promise<void>
}
