import { mock } from "jest-mock-extended";

import { ForwarderContext } from "../engine";

import { MailFlusher, MailFlusherSettings } from "./mailflusher";

describe("MailFlusher forwarder", () => {
  const context = mock<ForwarderContext<MailFlusherSettings>>();

  afterEach(() => {
    jest.resetAllMocks();
  });

  describe("authenticate", () => {
    it("returns a bearer header with the token", () => {
      context.authenticationToken.mockReturnValue("token");
      const result = MailFlusher.authenticate(null, context);

      expect(result).toEqual({ Authorization: "Bearer token" });
      expect(context.authenticationToken).toHaveBeenCalled();
    });
  });

  describe("settings", () => {
    it("should pass through deserialization", () => {
      const value: any = {};
      const result = MailFlusher.forwarder.settings.deserializer(value);
      expect(result).toBe(value);
    });
  });

  describe("importBuffer", () => {
    it("should pass through deserialization", () => {
      const value: any = {};
      const result = MailFlusher.forwarder.importBuffer.options.deserializer(value);
      expect(result).toBe(value);
    });
  });

  describe("createForwardingEmail", () => {
    describe("url", () => {
      it("returns the aliases endpoint appended to the context base URL", () => {
        context.baseUrl.mockReturnValue("");

        const result = MailFlusher.forwarder.createForwardingEmail.url(null, context);

        expect(result).toEqual("/api/v1/aliases");
      });
    });

    describe("body", () => {
      it("returns the domain and generated description", () => {
        context.emailDomain.mockReturnValue("johndoe.mailflusher.com");
        context.generatedBy.mockReturnValue("generated by");

        const result = MailFlusher.forwarder.createForwardingEmail.body(null, context);

        expect(context.generatedBy).toHaveBeenCalledWith(null, {
          extractHostname: true,
          maxLength: 200,
        });
        expect(result).toEqual({
          domain: "johndoe.mailflusher.com",
          description: "generated by",
        });
      });
    });

    describe("hasJsonPayload", () => {
      it.each([[200], [201]])("returns true when the status is %i", (status) => {
        const result = MailFlusher.forwarder.createForwardingEmail.hasJsonPayload(
          { status } as Response,
          context,
        );
        expect(result).toBeTruthy();
      });

      it.each([[400], [401], [403], [422], [500]])(
        "returns false when the status is %i",
        (status) => {
          const result = MailFlusher.forwarder.createForwardingEmail.hasJsonPayload(
            { status } as Response,
            context,
          );
          expect(result).toBeFalsy();
        },
      );
    });

    describe("processJson", () => {
      it("should read the email from the response", () => {
        const result = MailFlusher.forwarder.createForwardingEmail.processJson(
          { data: { email: "alias@johndoe.mailflusher.com" } },
          context,
        );

        expect(result).toEqual(["alias@johndoe.mailflusher.com"]);
      });

      it("returns [undefined] when the response shape is unexpected", () => {
        const result = MailFlusher.forwarder.createForwardingEmail.processJson({}, context);

        expect(result).toEqual([undefined]);
      });
    });
  });
});
