export type LogoutReason =
  | "accessTokenUnableToBeDecrypted"
  | "accountDeleted"
  | "invalidAccessToken"
  | "invalidSecurityStamp"
  | "keyConnectorError"
  | "logoutNotification"
  | "masterPasswordPolicyEnforcement"
  | "missingEmailError"
  | "noUnlockOptionsAvailable"
  | "passwordChanged"
  | "refreshTokenSecureStorageRetrievalFailure"
  | "sessionExpired"
  | "setInitialPassword"
  | "userInitiated"
  | "userKeyRotation"
  | "vaultTimeout";
