#!/usr/bin/env ts-node

/**
 * Builds icon font with Figma names directly (no remapping needed)
 * Handles icon variants for one-to-many mappings
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

import { FIGMA_VARIANTS } from "./migration-map";

const ICONS_DIR = path.join(__dirname, "../../libs/assets/src/material-icons");
const SCSS_PATH = path.join(__dirname, "../../libs/angular/src/scss/bwicons/styles/style.scss");
const ICON_TS_PATH = path.join(__dirname, "../../libs/components/src/shared/icon.ts");

function buildIconFont(): void {
  const variantFiles: string[] = [];

  try {
    // Step 1: Handle variants (copy files for one-to-many mappings)
    for (const [figmaName, variants] of Object.entries(FIGMA_VARIANTS)) {
      const sourcePath = path.join(ICONS_DIR, `${figmaName}.svg`);

      for (const variantName of variants) {
        const targetPath = path.join(ICONS_DIR, `${variantName}.svg`);

        if (fs.existsSync(sourcePath)) {
          fs.copyFileSync(sourcePath, targetPath);
          variantFiles.push(targetPath);
          // eslint-disable-next-line no-console
          console.log(`Created variant: ${variantName}.svg from ${figmaName}.svg`);
        }
      }
    }

    // Step 2: Generate icon font directly from Figma-named SVGs
    // eslint-disable-next-line no-console
    console.log("\nGenerating icon font...");
    execSync(
      'fantasticon libs/assets/src/material-icons -o libs/angular/src/scss/bwicons/fonts -t woff2 woff ttf svg -n bwi-font --selector ".bwi-%s" --normalize -h 1024 --descent 128',
      { stdio: "inherit" },
    );

    // Step 3: Update SCSS
    // eslint-disable-next-line no-console
    console.log("\nUpdating SCSS...");
    const jsonPath = path.join(
      __dirname,
      "../../libs/angular/src/scss/bwicons/fonts/bwi-font.json",
    );
    const glyphMap: Record<string, number> = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));

    const entries = Object.entries(glyphMap)
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([name, code]) => {
        const hex = code.toString(16);
        return `  "${name}": "\\${hex}"`;
      });

    const iconCount = entries.length;
    const iconsMapContent = `// Auto-generated - do not edit manually
$icons: (
${entries.join(",\n")}
);`;

    let scssContent = fs.readFileSync(SCSS_PATH, "utf-8");

    // Replace the $icons map - matches the pattern with or without comments
    const iconsMapRegex = /(?:\/\/[^\n]*\n)*\$icons: \([\s\S]*?\);/;
    scssContent = scssContent.replace(iconsMapRegex, iconsMapContent);

    fs.writeFileSync(SCSS_PATH, scssContent, "utf-8");

    // Step 4: Update TypeScript icon array
    // eslint-disable-next-line no-console
    console.log("\nUpdating TypeScript icon array...");
    const iconNames = Object.keys(glyphMap)
      .sort((a, b) => a.localeCompare(b))
      .map((name) => `  "bwi-${name}"`);

    const iconTsContent = `/**
 * Array of available Bitwarden Web Icons (bwi) font names.
 * These correspond to the actual icon names defined in the bwi-font.
 * This array serves as the single source of truth for all available icons.
 * Auto-generated by icons:build script - do not edit manually.
 */
export const BITWARDEN_ICONS = [
${iconNames.join(",\n")},
] as const;

/**
 * Type-safe icon names derived from the BITWARDEN_ICONS array.
 * This ensures type safety while allowing runtime iteration and validation.
 */
export type BitwardenIcon = (typeof BITWARDEN_ICONS)[number];
`;

    fs.writeFileSync(ICON_TS_PATH, iconTsContent, "utf-8");

    // Step 6: Cleanup temporary files
    // eslint-disable-next-line no-console
    console.log("\nCleaning up...");
    execSync("rm -f libs/angular/src/scss/bwicons/fonts/bwi-font.{css,html,json,ts}", {
      stdio: "inherit",
    });

    // eslint-disable-next-line no-console
    console.log("\n✓ Icon font build complete!");
    // eslint-disable-next-line no-console
    console.log(`  Generated ${iconCount} icons with Figma names`);
    // eslint-disable-next-line no-console
    console.log(`  Updated icon.ts with ${iconCount} icons`);
  } finally {
    // Step 7: Remove variant copies
    for (const variantFile of variantFiles) {
      if (fs.existsSync(variantFile)) {
        fs.unlinkSync(variantFile);
      }
    }
  }
}

buildIconFont();
