[workspace]
resolver = "2"
members = ["napi", "core", "proxy", "macos_provider", "windows-plugin-authenticator"]

[workspace.package]
version = "0.0.0"
license = "GPL-3.0"
edition = "2021"
publish = false

[workspace.dependencies]
aes = "=0.8.4"
anyhow = "=1.0.94"
arboard = { version = "=3.4.1", default-features = false }
argon2 = "=0.5.3" 
base64 = "=0.22.1"
bindgen = "0.71.1"
bitwarden-russh = { git = "https://github.com/bitwarden/bitwarden-russh.git", rev = "3d48f140fd506412d186203238993163a8c4e536" }
byteorder = "=1.5.0"
bytes = "1.9.0"
cbc = "=0.1.2" 
core-foundation = "=0.10.0"
dirs = "=6.0.0"
ed25519 =  "=2.2.3" 
embed_plist = "=1.2.2"
futures = "=0.3.31"
hex = "=0.4.3"
homedir = "=0.3.4"
interprocess = "=2.2.1" 
keytar = "=0.1.6"
libc = "=0.2.169"
log = "=0.4.25"
napi = "=2.16.15"
napi-build = "=2.1.4"
napi-derive = "=2.16.13"
oo7 = "=0.3.3"
oslog = "=0.2.0"
pin-project = "=1.1.8"
pkcs8 =  "=0.10.2" 
rand = "=0.8.5"
rsa = "=0.9.6"
russh-cryptovec = "=0.7.3"
scopeguard = "=1.2.0"
security-framework = "=3.1.0"
security-framework-sys = "=2.13.0"
serde = "=1.0.209"
serde_json = "=1.0.127"
sha2 = "=0.10.8"
simplelog = "=0.12.2"
ssh-encoding = "=0.2.0"
ssh-key = {version = "=0.6.7", default-features = false }
sysinfo = "0.33.1" 
thiserror = "=1.0.69"
tokio = "=1.43.0"
tokio-stream = "=0.1.15"
tokio-util = "=0.7.13"
typenum = "=1.17.0"
uniffi =  "=0.28.3"
widestring = "=1.1.0"
windows = "=0.58.0"
windows-registry = "=0.4.0"
zbus = "=4.4.0"
zbus_polkit = "=4.0.0"
