import {
  BitSvg,
  Import1PasswordIcon,
  Import1PasswordDarkIcon,
  ImportArcIcon,
  ImportAscendoIcon,
  ImportAvastIcon,
  ImportAviraIcon,
  ImportBitwardenIcon,
  ImportBlackberryIcon,
  ImportBlackberryDarkIcon,
  ImportBlurIcon,
  ImportBraveIcon,
  ImportButtercupIcon,
  ImportChromeIcon,
  ImportClipperzIcon,
  ImportCodebookIcon,
  ImportDashlaneIcon,
  ImportDashlaneDarkIcon,
  ImportDelineaIcon,
  ImportDelineaDarkIcon,
  ImportEdgeIcon,
  ImportEncryptrIcon,
  ImportEnpassIcon,
  ImportFSecureIcon,
  ImportFirefoxIcon,
  ImportGnomeIcon,
  ImportKasperskyIcon,
  ImportKeepassIcon,
  ImportKeeperIcon,
  ImportLastpassIcon,
  ImportMsecureIcon,
  ImportMykiIcon,
  ImportNetwrixIcon,
  ImportNordpassIcon,
  ImportOperaIcon,
  ImportPadlockIcon,
  ImportPassboltIcon,
  ImportPasskeepIcon,
  ImportPasskyIcon,
  ImportPassmanIcon,
  ImportPasspackIcon,
  ImportPasspackDarkIcon,
  ImportPasswordAgentIcon,
  ImportPasswordBossIcon,
  ImportPasswordDepotIcon,
  ImportPasswordSafeIcon,
  ImportPasswordXpIcon,
  ImportProtonpassIcon,
  ImportPsonoIcon,
  ImportRemembearIcon,
  ImportRoboformIcon,
  ImportSafariIcon,
  ImportSafeincloudIcon,
  ImportSaferpassIcon,
  ImportSecuresafeIcon,
  ImportSplashidIcon,
  ImportStickyPasswordIcon,
  ImportTruekeyIcon,
  ImportVivaldiIcon,
  ImportYotiIcon,
  ImportZohoIcon,
} from "@bitwarden/assets/svg";

import { ImportType } from "../../models";

/** Picker vendor icons, kept in their own icon-importing module — deliberately separate from
 *  `picker-vendor-data.ts` (displayName/formats/`isPickerVendor`), so that consumers which don't
 *  render an icon (e.g. `canActivateImportType`, wired into every client's eagerly-loaded root
 *  routing module) can import `picker-vendor-data.ts` directly and never pull the vendor icon set
 *  into their bundle. No re-export here in either direction — `ImportSourceSelectComponent` (the
 *  only consumer of this module) imports both modules directly. */
interface PickerVendorIcon {
  /** Vendor logo. Absent ids fall back to a generic icon tile in the picker. */
  icon?: BitSvg;
  /** Dark-theme variant of `icon`, for vendors whose mark is a single fixed color that would be
   *  low-contrast against a dark background (e.g. a navy wordmark meant for a light card). Only
   *  set where the vendor actually supplied one — most marks are full-color and theme-agnostic. */
  darkIcon?: BitSvg;
}

const PICKER_VENDOR_ICONS: Partial<Record<ImportType, PickerVendorIcon>> = {
  bitwardenjson: { icon: ImportBitwardenIcon },
  chromecsv: { icon: ImportChromeIcon },
  dashlanecsv: { icon: ImportDashlaneIcon, darkIcon: ImportDashlaneDarkIcon },
  firefoxcsv: { icon: ImportFirefoxIcon },
  keepass2xml: { icon: ImportKeepassIcon },
  keepassxcsv: { icon: ImportKeepassIcon },
  keeper: { icon: ImportKeeperIcon },
  lastpasscsv: { icon: ImportLastpassIcon },
  safaricsv: { icon: ImportSafariIcon },
  "1password1pux": { icon: Import1PasswordIcon, darkIcon: Import1PasswordDarkIcon },
  roboformcsv: { icon: ImportRoboformIcon },
  enpasscsv: { icon: ImportEnpassIcon },
  protonpass: { icon: ImportProtonpassIcon },
  safeincloudxml: { icon: ImportSafeincloudIcon },
  pwsafexml: { icon: ImportPasswordSafeIcon },
  stickypasswordxml: { icon: ImportStickyPasswordIcon },
  msecurecsv: { icon: ImportMsecureIcon },
  truekeycsv: { icon: ImportTruekeyIcon },
  passwordbossjson: { icon: ImportPasswordBossIcon },
  zohovaultcsv: { icon: ImportZohoIcon },
  splashidcsv: { icon: ImportSplashidIcon },
  padlockcsv: { icon: ImportPadlockIcon },
  passboltcsv: { icon: ImportPassboltIcon },
  clipperzhtml: { icon: ImportClipperzIcon },
  aviracsv: { icon: ImportAviraIcon },
  saferpasscsv: { icon: ImportSaferpassIcon },
  ascendocsv: { icon: ImportAscendoIcon },
  passkeepcsv: { icon: ImportPasskeepIcon },
  arccsv: { icon: ImportArcIcon },
  edgecsv: { icon: ImportEdgeIcon },
  operacsv: { icon: ImportOperaIcon },
  vivaldicsv: { icon: ImportVivaldiIcon },
  bravecsv: { icon: ImportBraveIcon },
  passwordagentcsv: { icon: ImportPasswordAgentIcon },
  passpackcsv: { icon: ImportPasspackIcon, darkIcon: ImportPasspackDarkIcon },
  passmanjson: { icon: ImportPassmanIcon },
  avastcsv: { icon: ImportAvastIcon },
  fsecurefsk: { icon: ImportFSecureIcon },
  kasperskytxt: { icon: ImportKasperskyIcon },
  securesafecsv: { icon: ImportSecuresafeIcon },
  blackberrycsv: { icon: ImportBlackberryIcon, darkIcon: ImportBlackberryDarkIcon },
  buttercupcsv: { icon: ImportButtercupIcon },
  codebookcsv: { icon: ImportCodebookIcon },
  yoticsv: { icon: ImportYotiIcon },
  nordpasscsv: { icon: ImportNordpassIcon },
  psonojson: { icon: ImportPsonoIcon },
  passkyjson: { icon: ImportPasskyIcon },
  passwordxpcsv: { icon: ImportPasswordXpIcon },
  netwrixpasswordsecure: { icon: ImportNetwrixIcon },
  passworddepot17xml: { icon: ImportPasswordDepotIcon },
  delineaxml: { icon: ImportDelineaIcon, darkIcon: ImportDelineaDarkIcon },
  gnomejson: { icon: ImportGnomeIcon },
  blurcsv: { icon: ImportBlurIcon },
  remembearcsv: { icon: ImportRemembearIcon },
  mykicsv: { icon: ImportMykiIcon },
  encryptrcsv: { icon: ImportEncryptrIcon },
  // No vendor art supplied for: passworddragonxml, upmcsv, meldiumcsv, passwordwallettxt,
  // logmeoncecsv — generic icon tile in the picker.
};

export function pickerIconFor(id: string, isDark: boolean): BitSvg | undefined {
  const icons = PICKER_VENDOR_ICONS[id as ImportType];
  return (isDark ? icons?.darkIcon : undefined) ?? icons?.icon;
}
