export const FieldRole = Object.freeze({
  Username: "username",
  CurrentPassword: "currentPassword",
  UpdateCurrentPassword: "updateCurrentPassword",
  NewPassword: "newPassword",
  Email: "email",
  Totp: "totp",
  CardholderName: "cardholderName",
  CardNumber: "cardNumber",
  CardExpirationDate: "cardExpirationDate",
  CardExpirationMonth: "cardExpirationMonth",
  CardExpirationYear: "cardExpirationYear",
  CardCvv: "cardCvv",
  IdentityTitle: "identityTitle",
  IdentityFirstName: "identityFirstName",
  IdentityMiddleName: "identityMiddleName",
  IdentityLastName: "identityLastName",
  IdentityFullName: "identityFullName",
  IdentityAddress1: "identityAddress1",
  IdentityAddress2: "identityAddress2",
  IdentityAddress3: "identityAddress3",
  IdentityCity: "identityCity",
  IdentityState: "identityState",
  IdentityPostalCode: "identityPostalCode",
  IdentityCountry: "identityCountry",
  IdentityCompany: "identityCompany",
  IdentityPhone: "identityPhone",
  IdentityEmail: "identityEmail",
  IdentityUsername: "identityUsername",
} as const);
export type FieldRole = (typeof FieldRole)[keyof typeof FieldRole];
