[package]
name = "windows-plugin-authenticator"
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }
publish = { workspace = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
bindgen = "0.71.1"
