name: Auto Update Branch

on:
  push:
    branches:
      - 'main'
      - 'rc'
    paths:
      - 'apps/web/**'
      - 'libs/**'
      - '*'
      - '!*.md'
      - '!*.txt'
      - '.github/workflows/build-web.yml'
  workflow_dispatch:
    inputs: {}

jobs:
  update:
    name: Update Branch
    runs-on: ubuntu-22.04
    env:
      _BOT_EMAIL: 106330231+bitwarden-devops-bot@users.noreply.github.com
      _BOT_NAME: bitwarden-devops-bot
    permissions:
      contents: write
    steps:
      - name: Setup
        id: setup
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: 'eu-web-${{ steps.setup.outputs.branch }}'
          fetch-depth: 0
          persist-credentials: true

      - name: Merge ${{ steps.setup.outputs.branch }}
        env:
          _BRANCH: ${{ steps.setup.outputs.branch }}
        run: |
          git config --local user.email "$_BOT_EMAIL"
          git config --local user.name "$_BOT_NAME"
          git merge "origin/$_BRANCH"
          git push
